name: hotel_booking_application
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  google_fonts:
  cloud_firestore:
  firebase_core:
  firebase_auth:
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hotel_book.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/hotel.png
    - assets/images/hotel_book.png
    - assets/images/google.png
